"""new fields in user model

Revision ID: 211db3640ea0
Revises: af49769332b9
Create Date: 2020-05-24 20:43:37.173085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211db3640ea0'
down_revision = 'af49769332b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
